[config]
    default-lang = "en"

[lang.en]
    title = "Palatino"
    context = "Georgia"
    math = "Times New Roman"

[lang.zh]
    title = "STKaiti"
    context = "Songti SC"
    math = "Kaiti SC"
