[paper]
    note = "a4"
    booklet = "iso-b5"

[fonts.en]
    chapter = "Palatino"
    chapter-index = "Palatino"
    cover = "Palatino"
    author = "Times New Roman"
    date = "Times New Roman"
    epigraph = "Georgia"
    preface = "Georgia"
    contents = "Georgia"
    context = "Georgia"
    part = "Georgia"
    math = "Times New Roman"

[fonts.zh]
    chapter = "STKaiti"
    chapter-index = "STKaiti"
    cover = "STKaiti"
    author = "Kaiti SC"
    date = "Kaiti SC"
    epigraph = "Songti SC"
    preface = "Songti SC"
    contents = "Songti SC"
    context = "Songti SC"
    part = "Songti SC"
    math = "Kaiti SC"

[sizes.en]
    chapter = 24
    chapter-index = 50
    cover = 36
    author = 24
    date = 18
    epigraph = 16
    heading-1 = 16
    heading-2 = 14
    heading-3 = 12
    heading-4 = 10.5
    context = 10.5
    header = 8
    footer = 8

[sizes.zh]
    chapter = 24
    chapter-index = 50
    cover = 36
    author = 24
    date = 18
    heading-1 = 16
    heading-2 = 14
    heading-3 = 12
    heading-4 = 10.5
    context = 10.5
    header = 8
    footer = 8

[spaces.en]
    par-indent = 2
    par-leading = 1
    par-spacing = 1
    list-indent = 1.2
    block-above = 1
    block-below = 1
    contents-indent = 1.2

[spaces.zh]
    par-indent = 2
    par-leading = 1
    par-spacing = 1
    list-indent = 2
    block-above = 1
    block-below = 1
